# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c30492435257f91b2655dd95a036c3cf22e6297900dd309d32cc101610c9dac8dfb73b7725b65757ffcaa1d1ebf45eba32135abdfc21acda5e91a0a6f2a6be

test:
  secret_key_base: 067450c35c1121eafd5e3e95a61f412c9e0cc648a61a7d59e3414021b61952d88b79914d6afaed666dd71cb8d90799dd9240ea323aee3a41533c7833de2adcf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
